navbar fix
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-PokeKwak pull request #29
Opened 2023-10-26 14:03 UTC by bayram-69

2023-10-26 14:07 UTC, PierreA44 approved these changes

2023-10-26 14:29 UTC, ioayoub requested changes

2023-10-26 14:29 UTC, ioayoub commented on frontend/src/App.jsx
> +  const [panierCount, setPanierCount] = useState(0);
FrenchGlish is not allowed here, maybe "basketCount, setBasketCount" ? ;)

2023-10-26 14:29 UTC, ioayoub commented on frontend/src/components/navbar/Navbar.jsx
> +function Navbar({ panierCount }) {
Check App.jsx request

2023-10-27 10:56 UTC, ioayoub approved these changes

2023-10-27 10:57 UTC, merged