Passage des Filtres dans Cardlist, fix de soucis responsivité css
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-PokeKwak pull request #35
Opened 2023-10-27 15:13 UTC by Jhanemba64

2023-10-27 15:18 UTC, bayram-69 approved these changes

2023-10-27 15:18 UTC, PierreA44 approved these changes

2023-10-27 15:43 UTC, akornne approved these changes

2023-10-31 11:09 UTC, akornne approved these changes

2023-11-03 15:03 UTC, ioayoub requested changes

2023-11-03 15:03 UTC, ioayoub commented on frontend/src/components/CardList/CardList.jsx
> +        <Filtres />
👀

2023-11-03 15:03 UTC, ioayoub commented on frontend/src/components/CardList/CardList.jsx
> +import Filtres from "../filtres/Filtres";
👀

2023-11-08 08:22 UTC, closed without merging