Adding router
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-PokeKwak pull request #39
Opened 2023-11-01 12:01 UTC by Jhanemba64

2023-11-01 12:01 UTC, akornne approved these changes

2023-11-01 12:02 UTC, PierreA44 approved these changes

2023-11-01 12:02 UTC, bayram-69 approved these changes

2023-11-01 12:50 UTC, ioayoub requested changes
Some required changes are commented.
Avoid also using empty components (ex: Homepage) they're useless here.

2023-11-01 12:50 UTC, ioayoub commented on frontend/src/App.jsx
> +      <Outlet setBasketCount={setBasketCount} />
Never pass a props to the Outlet (unless you really know what you're doing) , your App.jsx is not designed to handle states.

2023-11-01 12:50 UTC, ioayoub commented on frontend/src/components/CardList/CardList.jsx
> +      <Filtres />
All component's names must be in english

2023-11-01 12:50 UTC, ioayoub commented on frontend/src/main.jsx
> +            element: <CardPage />,
You add directly the loader here to fetch your datas, unless I missed something?

2023-11-03 15:01 UTC, ioayoub approved these changes

2023-11-03 17:19 UTC, merged