Added Pokedeck
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-PokeKwak pull request #52
Opened 2023-11-10 08:32 UTC by PierreA44

2023-11-10 08:44 UTC, bayram-69 approved these changes

2023-11-10 09:00 UTC, akornne approved these changes

2023-11-10 09:07 UTC, ioayoub requested changes

2023-11-10 09:07 UTC, ioayoub commented on frontend/src/components/modal/Modal.jsx
> +      favoriteCard.push(newFavoriteItem);
As discussed, this must be fixed

2023-11-11 11:04 UTC, Jhanemba64 approved these changes

2023-11-13 13:50 UTC, ioayoub approved these changes

2023-11-13 13:54 UTC, merged