feat: add filters
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-PokeKwak pull request #65
Opened 2023-11-13 18:15 UTC by akornne

2023-11-14 13:13 UTC, Jhanemba64 approved these changes

2023-11-14 13:14 UTC, bayram-69 approved these changes

2023-11-14 13:16 UTC, PierreA44 approved these changes

2023-11-14 14:54 UTC, ioayoub requested changes
As discussed, please improve your improve your filters

2023-11-16 13:36 UTC, ioayoub approved these changes

2023-11-16 13:36 UTC, merged