feat : add CardPage and many features
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-PokeKwak pull request #66
Opened 2023-11-14 22:12 UTC by PierreA44

2023-11-15 08:55 UTC, akornne approved these changes

2023-11-15 08:56 UTC, Jhanemba64 approved these changes

2023-11-15 08:57 UTC, bayram-69 approved these changes

2023-11-15 09:59 UTC, ioayoub requested changes
Remove this useless setPresent state, you can easily add new property to your objects

2023-11-15 09:59 UTC, ioayoub commented on frontend/src/components/modal/Modal.jsx
> +      setPresent(true);
You can add a new property to your current object. No need to use a state here.

2023-11-16 16:18 UTC, ioayoub approved these changes

2023-11-16 16:18 UTC, merged